channels:
  - conda-forge

dependencies:
  # Python version and pip
  - python=3.10
  - pip

  # Requirements for airavata cerebrum
  - anndata
  - anywidget
  - duckdb
  - ipywidgets
  - ipytree
  - leidenalg
  - jupyter
  - nest-simulator
  - numba
  - numpy
  - marimo
  - matplotlib
  - openmpi-mpicc
  - openpyxl
  - pandas
  - pyarrow
  - pydantic
  - pyqtgraph
  - python-dateutil
  - python-igraph
  - python-jsonpath
  - pyyaml
  - requests
  - scikit-learn
  - scanpy
  - scipy
  - sqlglot
  - sqlalchemy
  - traitlets
  - tqdm

  # PIP dependencies
  - pip:
      - allensdk
      - bmtk
      - mpi4py
      - parse
      - polars
      - pylightxl
      - git+https://github.com/alleninstitute/abc_atlas_access
      - git+https://github.com/alleninstitute/neuroanalysis
      - git+https://github.com/alleninstitute/aisynphys
